package sgfutils

const (
	SGFTagAddBlack    = "AB"
	SGFTagAddWhite    = "AW"
	SGFTagAnnotations = "AN"
	SGFTagApplication = "AP"
	SGFTagBlackMove   = "B"
	SGFTagBlackRank   = "BR"
	SGFTagBlackTeam   = "BT"
	SGFTagComment     = "C"
	SGFTagCopyright   = "CP"
	SGFTagDate        = "DT"
	SGFTagEvent       = "EV"
	SGFTagFileFormat  = "FF"
	SGFTagGame        = "GM"
	SGFTagGameName    = "GN"
	SGFTagHandicap    = "HA"
	SGFTagKomi        = "KM"
	SGFTagOpening     = "ON"
	SGFTagOvertime    = "OT"
	SGFTagBlackName   = "PB"
	SGFTagPlace       = "PC"
	SGFTagPlayer      = "PL"
	SGFTagWhiteName   = "PW"
	SGFTagResult      = "RE"
	SGFTagRound       = "RO"
	SGFTagRules       = "RU"
	SGFTagSource      = "SO"
	SGFTagSize        = "SZ"
	SGFTagTimelimit   = "TM"
	SGFTagUser        = "US"
	SGFTagWhiteMove   = "W"
	SGFTagWhiteRank   = "WR"
	SGFTagWhiteTeam   = "WT"

	// Additional
	SGFTagTriangle = "TR"
	SGFTagSquare   = "SQ"
	SGFTagCircle   = "CR"
	SGFTagX        = "MA"
	SGFTagLabel    = "LB"
)
